apiVersion: batch/v1
kind: Job
metadata:
  name: fishky-migrate
  namespace: fishky
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migrate
          image: ghcr.io/kompot-rar/fishky-backend:latest
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fishky-secrets
                  key: DATABASE_URL
