apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kompot-rar/kubernetes.git
    targetRevision: HEAD
    path: manifests/blog-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
