apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.1.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.k3s
        
        prometheus:
          prometheusSpec:
            retention: 30d
            serviceMonitorSelectorNilUsesHelmValues: false
            
            additionalScrapeConfigs:
              - job_name: 'proxmox-nodes'
                scrape_interval: 30s # TYMCZASOWO: krótki interwał dla debugowania
                static_configs:
                  - targets:
                    - '10.0.10.11:9100'
                    - '10.0.10.12:9100'
                    - '10.0.10.13:9100'
              - job_name: 'proxmox-smart'
                scrape_interval: 30s # TYMCZASOWO
                static_configs:
                  - targets:
                    - '10.0.10.11:9100'
                    - '10.0.10.12:9100'
                    - '10.0.10.13:9100'

            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
            
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false

        alertmanager:
          enabled: true
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
