apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.1.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: true
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.k3s
        
        # Wyłączamy webhooki, które dublują zasoby RBAC i obciążają klaster
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
        
        alertmanager:
          enabled: true
        
        nodeExporter:
          enabled: true
        
        # Włączamy zbieranie metryk z samego k3s
        kubeStateMetrics:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
