apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartctl-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.13.0
    chart: prometheus-smartctl-exporter
    helm:
      values: |
        serviceMonitor:
          enabled: true
          namespace: monitoring
          additionalLabels:
            release: monitoring
            app: kube-prometheus-stack
          # Próbujemy obu popularnych nazw portów, żeby mieć pewność
          endpoints:
            - port: https-metrics
              interval: 30s
            - port: http-metrics
              interval: 30s

        config:
          interval: 60s
        
        hostNetwork: true
        privileged: true
        
        extraVolumeMounts:
          - name: dev
            mountPath: /dev
        extraVolumes:
          - name: dev
            hostPath:
              path: /dev
        
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
